config/routes.rb
CalendarV4::Application.routes.draw do

  match "/sessions/create" => 'sessions#create'
  match "sessions/destroy" => 'sessions#destroy'
  match "/reservations/:id/edit/delete_multiple" => 'reservations#delete_multiple'
  match "/reservations/:id/edit/update_multiple" => 'reservations#update'
  match "/reservations/:id/update_multiple" => 'reservations#update'
  match "/reservations/:id/update" => 'reservations#update'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/a/goodinc.com/o8/ud" => "sessions#create"
      resources :reservations
      resources :sessions, :only => [:create, :destroy, :new]
      resources :reservations do
        member do
          post :delete_multiple
          put :update_multiple
        end 
        collection do 
          post :delete_multiple
          put :update_multiple
        end
      end

   root :to => 'reservations#index'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  has_one :recurrance
  attr_accessible :date, :recur, :recurrance_duration, :room, :time_in, :time_out, :id, :recurrance_id, :createdby
  validates_presence_of :room, :date
  validate :validate_start_time
  validate :validate_previous_reservations
  validate :minimum_duration
  validate :validate_date
  after_save :update_attr
  after_create :create_recurrance 

  ROOMLIST = %w[Ops GoodCorps Interview1]
  RECURRANCE_OPTIONS = %w[None Weekly Bi-Weekly Monthly]
  DURATION_OPTIONS = %w[ 0 1 2 3 4 8 12 24 indefinite]

    def update_attr
      if recurrance_id == nil
        self.update_attributes(:recurrance_id => self.id)
        self.save(:validate => false)
      end
    end

    def create_recurrance
      if recur == "Weekly"
        x = Recurrance.create(start_date: date, time_in: time_in, time_out: time_out, 
                          room: room, recur: recur, duration: recurrance_duration, parent_id: id )
      end
    end

    def validate_start_time
  	  if (time_in > time_out)
  	    errors.add(:time_in, "is after End time. What are you, traveling in time?") 
   	  end
    end

    def validate_date
      if date == nil 
        errors.add(:date, "You must choose a date")
      elsif date < Date.today
	      errors.add(:date, "Cannot reserve room in the past, son!")
	    end 
    end

    def minimum_duration
      minutes = 15 * 60
      if (time_out - time_in < minutes )
        errors.add(:time_out, "Ain't no meeting that's shorter than 15 minutes.")
      end
    end

    def validate_previous_reservations
	  conflicts = Reservation.where(:room => room, :date => date, 
                :time_in => time_in...time_out)
      errors.add(:room, "Room conflict") if conflicts.present?
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  #before_filter :authorize
  include ReservationsControllerHelper

  def index
    @reservations = Reservation.all
    @reserv = Reservation.where(:date => Date.today)
    @recurrances = Recurrance.all
    @exclusions = Exclusion.all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def create
    @reservation = Reservation.new(params[:reservation])
    @reservation.createdby = session[:email]
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservations_url, notice: 'Reservation was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def new
  	@reservation = Reservation.new
    respond_to do |format|
      format.html
    end
  end

  def edit

    @reservation = Reservation.find(params[:id])
    find_recurrances(@reservation)

    respond_to do |format|
      format.html
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    find_recurrances(@reservation)

    if params[:reservation_ids]
      @ids = params[:reservation_ids][0].split(" ")
      @reservations = Reservation.find(@ids)
      @reservations.each do |reservation|
        time_in = Time.new(params[:reservation]['time_in(1i)'].to_i,
                           params[:reservation]['time_in(2i)'].to_i,
                           params[:reservation]['time_in(3i)'].to_i,
                           params[:reservation]['time_in(4i)'].to_i,
                           params[:reservation]['time_in(5i)'].to_i )

        time_out = Time.new(params[:reservation]['time_out(1i)'].to_i,
                           params[:reservation]['time_out(2i)'].to_i,
                           params[:reservation]['time_out(3i)'].to_i,
                           params[:reservation]['time_out(4i)'].to_i,
                           params[:reservation]['time_out(5i)'].to_i)
        reservation.room = params[:reservation]["room"]
        reservation.time_in = time_in
        reservation.time_out = time_out
        reservation.save
      end
    else
      @reservation.update_attributes(params[:reservation])
    end
    respond_to do |format|
        format.html { redirect_to reservations_url }
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    find_recurrances(@reservation)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def delete_multiple
    if params[:reservation_ids] #should be adapted to fit any size of ID, eg. id of 100,000
      params[:reservation_ids] = params[:reservation_ids][0].split(" ")
    else
       redirect_to reservations_url
    end
    @reservations = Reservation.find(params[:reservation_ids])
    @recurrance_id = @reservations.first.recurrance_id
    @parent_id = @recurrance_id
    @recurrance = Recurrance.find_by_parent_id(@parent_id)
    @exclusions = Exclusion.where(recurrance_id: @parent_id)
    if @exclusions.count > 0
      if @exclusions.count == @recurrance.duration
        @recurrance.destroy
        @exclusions.each do |x|
          x.destroy
        end
      end
    end

    @reservations.each do |x|
      x.destroy
    end
    respond_to do |format|
      format.html { redirect_to reservations_url }
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url }
    end
  end

  private
  def authorize
    if session[:official] != true
      render 'shared/signin'
    end
  end

end

app/views/reservations/_calendar.html.erb
<div id="calendar_wrapper">
	<%= link_to 'Create Reservation', new_reservation_path, :id => "create_button" %>
	<h1>GOOD Reservations</h1>
	<h2 id="month">
	  <% calendar_header %>
	  <% week_limit %>
	  <%= link_to '<', reservations_path(:date => @date.prev_month.at_beginning_of_month, :limit => @limit) %>
	  <%= format_month(@date) %>
	  <%= link_to '>', reservations_path(:date => @date.next_month.at_beginning_of_month, :limit => @limit) %>  
	</h2>
	<h3 id="week_adder">
		<%= render 'week_adder' %>
	</h3>
	<table id="calendar">
		<% headers = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday] %>
		<% headers.each do |day_name| %>
			<%= content_tag(:th, day_name) %>
		<% end %>
		<%= render_weeks(@date, @limit) %>
	</table>
</div>

app/views/reservations/_controls.html.erb
<%= link_to 'Create Reservation', new_reservation_path %>
<%= link_to 'Back', reservations_path %>

app/views/reservations/_day.html.erb
<% collection.each do |day_reservations| %>
	<p class="single_reserv">
	<%= create_day(day_reservations) %>
<% end %>

app/views/reservations/_delete_options.html.erb
<div id="delete_options_wrapper">
	<div class="delete_options clearfix">
		<div class= "delete_options_header">Associated Recurring Reservations</div>
		<%= form_tag 'delete_multiple' do %>	
			<% if @associated_recurrances.length > 1 %>
				<% @associated_recurrances.each do |assoc_recur|%>
				  <div class="options">
				    <%= check_box_tag("reservation_ids[]", assoc_recur.id, false)%>
				    <%= assoc_recur.date %>
				  </div>
				<% end %>
				<div class="options">
					<%= check_box_tag("reservation_ids[]", @id_list, false) %>All
				</div>
			<% else %>
			    <div class="options">
					<%= check_box_tag("reservation_ids[]", @reservation.id, false) %>
					<%= "This reservation" %>
				</div>
			<% end %>
			<%= submit_tag "Delete Selected", id: "DeleteSelectedButton" %>
		<% end %>
	</div>
</div>

app/views/reservations/_form.html.erb
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.2/jquery-ui.js" %>
<%= form_for @reservation do |f| %>
  <fieldset id="create_reserv_form">
    <% if @reservation.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
            <ul>
            <% @reservation.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
    <% end %>
      <%= f.label :date %>
      <%= f.text_field :date, id: "datepicker", :placeholder => "Pick a date" %>
      <%= f.label 'Time-In' %>
      <%= f.time_select :time_in, {:minute_step => 15, :ampm => true }, class: "timepicker", id: 'time_in' %>
      <%= f.label 'Time-Out' %>
      <%= f.time_select :time_out, {:minute_step => 15, :ampm => true }, class: "timepicker", id: 'time_out' %>
      <%= f.label :room %>
      <%= f.select :room, Reservation::ROOMLIST, id: 'room' %>
      <%= f.label 'Recurring' %>
      <%= f.select :recur, Reservation::RECURRANCE_OPTIONS, id: 'recur' %>
      <%= f.label 'How many times?' %>
      <%= f.select :recurrance_duration, Reservation::DURATION_OPTIONS, id: 'duration' %>
      <%= f.submit :id => "create_reserv_button" %> <br>
  </fieldset>
<% end %>

app/views/reservations/_index.html.erb
<% @recurrances.each do |recur| %>
	<div>
	  	<%= recur.to_s %>
	</div>
<% end %> 

<% @reservations.each do |reserv| %>
	  <div>
	  	<%= reserv.date %>
	  	<%= reserv.id.to_s %>
	  	<%= 'recurrance_id=' + reserv.recurrance_id.to_s %>
	  </div>
<% end %>

<% @exclusions.each do |exclusion| %>
	<div>
		<%= "Exclusion ID: " + exclusion.recurrance_id.to_s %>
		<%= "Date Excluded " + exclusion.reserv_exclusion.to_s %>
	</div>
<% end %>

app/views/reservations/_recur_form.html.erb
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.2/jquery-ui.js" %>
<%= form_for @reservation do |f| %>
  <fieldset id="create_reserv_form">
    <% if @reservation.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
            <ul>
            <% @reservation.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
    <% end %>
      <p> Edit Recurring Reservation

      <%= f.label :date %>
      <%= f.text_field :date, id: "datepicker", :placeholder => "Pick a date" %>
      <%= f.label 'Time-In' %>
      <%= f.time_select :time_in, {:minute_step => 15, :ampm => true, :value => @reservation.time_in.localtime, 
                                  :default => Time.now.localtime}, class: "timepicker", id: 'time_in' %>
      <%= f.label 'Time-Out' %>
      <%= f.time_select :time_out, {:minute_step => 15, :ampm => true, :value => @reservation.time_out.localtime, 
                                  :default => Time.now.localtime + 1.hour}, class: "timepicker", id: 'time_out' %>
      <%= f.label "place where shit happens" %>
      <%= f.select :room, Reservation::ROOMLIST, id: 'room' %>
      <%= f.label 'Recurring' %>
      <%= f.select :recur, Reservation::RECURRANCE_OPTIONS, id: 'recur' %>
      <%= f.label 'How many times?' %>
      <%= f.select :recurrance_duration, Reservation::DURATION_OPTIONS, id: 'duration' %>
      <%= render 'update_options' %>
  </fieldset>
<% end %>

app/views/reservations/_update_options.html.erb
<div class="update_multiple_wrapper">
  <div class="clearfix">
    <div class="options_header">Associated Recurring Reservations</div>
    <%= form_tag 'update' do %>  
      <% if @associated_recurrances.length > 1 %>
        <% @associated_recurrances.each do |assoc_recur|%>
          <div class="update_options">
            <%= check_box_tag("reservation_ids[]", assoc_recur.id, false, :class => "reserv_updates")%>
            <%= assoc_recur.date %>
          </div>
        <% end %>
        <div class="update_options">
          <%= check_box_tag("reservation_ids[]", @id_list, false, :class => "reserv_updates") %>All
        </div>
      <% else %>
          <div class="update_options">
          <%= check_box_tag("reservation_ids[]", @reservation.id, false, :class => "reserv_updates") %>
          <%= "This reservation" %>
        </div>
      <% end %>
      <%= submit_tag "Update Selected", id: "UpdateSelectedButton" %>
    <% end %>

  </div>
</div>

app/views/reservations/_week.html.erb
<% headers = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] %>
<% i = 0 %>

<% headers.each do |day| %>
	<% if @date_range[i] == Date.today %>
		<%= create_cell(i, @date_range, "today") %>
		<% i = i + 1 %>
	<% elsif @date_range[i].month != Time.now.month %>
		<%= create_cell(i, @date_range, "not_in_month") %>
		<% i = i + 1 %>
	<% else %>
		<%= create_cell(i, @date_range, "not_today") %>
	<% i = i + 1 %>
	<% end %>
<% end %>

app/views/reservations/_week_adder.html.erb
<%= link_to 'remove one week', reservations_path(:limit => @limit - 1) %>
<%= link_to 'see another week', reservations_path(:limit => @limit + 1) %>
<%= link_to 'see whole month', reservations_path(:limit => 3) %>

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>
<div>
	<% if params[:class] == "recurrance" %>
		<%= render 'recur_form' %>
		<div class="option_button_wrapper">
			<%= link_to "Update Options", @reservation, :action => "display_update_options", 
									  :remote => true, :id => "display_update_options", :class => "options_button" %>
		</div>
		<div class="option_button_wrapper">
			<%= link_to "Delete Options", @reservation, :action => "display_delete_options", 
	      :remote => true, :id => 'display_delete_options', :class => "options_button" %>
	    </div>
		<div class="delete_partial_zone">
		  <%= render 'delete_options' %>
		</div>

	<% else %>
		<%= render 'form' %>
		<div class="back_button_wrapper">
    		<%= link_to 'Delete Reservation', @reservation, method: :delete, :class => "back_button", id: "delete_single_reserv", data: { confirm: 'Are you sure?' } %> 
  		</div>
	<% end %>
	
	<div class="back_button_wrapper">
	<%= link_to "Back", reservations_path, :class => "back_button" %>
	</div>
</div>

app/views/reservations/index.html.erb
<%= render 'calendar' %>

app/views/reservations/new.html.erb
<div class="form_wrapper">
	<%= render 'form' %>
	<%= link_to 'Back', reservations_path %>
</div>

app/views/reservations/show.html.erb
<div class="form_wrapper">
	<%= render 'form' %>
	<%= render 'delete_options' %>
	<%= link_to 'Back', reservations_path %>
</div>